[tcpserver]
enable=0
host=127.0.0.1
port=8071

[udpserver]
enable=1
host=127.0.0.1
port=8075

[data-huailin]
enable=0
type=pg
host=172.17.0.10
port=35432
user=powerforecast
password=REPLACE_WITH_PASSWORD
database=powerforecast
sql_short_term=SELECT * FROM hdrfcstdata_hxgf WHERE fcst_time BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';
sql_super_short_term=SELECT * FROM hdrsfcstdata_hxgf WHERE fcst_time BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';

[data-hexu]
enable=0
type=mysql
host=172.17.108.30
port=3306
user=sa
password=REPLACE_WITH_PASSWORD
# MySQL 可选。若 SQL 里写了 schema.table，可留空。
database=
sql_short_term=SELECT * FROM dwd.dwd_forecast_wf_short_term_partition WHERE forecast_date BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';
sql_super_short_term=SELECT * FROM dwd.dwd_forecast_wf_ultra_short_term WHERE forecast_date BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';

[data-local-pg]
enable=1
type=pg
host=127.0.0.1
port=5433
user=postgres
password=limit123
database=powerforecast
sql_short_term=SELECT * FROM dwd_forecast_wf_short_term_partition WHERE forecast_date BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';
sql_super_short_term=SELECT * FROM dwd_forecast_wf_ultra_short_term WHERE forecast_date BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';


[data-local-mysql]
enable=1
type=mysql
host=127.0.0.1
port=3306
user=root
password=123456
# MySQL 可选。若 SQL 里写了 schema.table，可留空。
database=powerforecast
sql_short_term=SELECT * FROM hdrfcstdata_hxgf WHERE fcst_time BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';
sql_super_short_term=SELECT * FROM hdrsfcstdata_hxgf WHERE fcst_time BETWEEN '2026-03-01 00:00:00' AND '2026-03-03 00:00:00';
